In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

In [2]:
digits=load_digits()

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.1)

In [4]:
lr=LogisticRegression(solver='liblinear', max_iter=1000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9722222222222222

In [5]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9888888888888889

In [6]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9833333333333333

In [7]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [9]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [10]:
get_score(LogisticRegression(solver='liblinear', max_iter=1000),X_train,X_test,y_train,y_test)

0.9722222222222222

In [11]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9888888888888889

In [12]:
get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test)

0.9833333333333333

In [13]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [14]:
scores_l=[]
scores_svm=[]
scores_rf=[]

for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]                                      
    scores_l.append(get_score(LogisticRegression(solver='liblinear', max_iter=1000),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

In [15]:
scores_l

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [16]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [17]:
scores_rf

[0.9382303839732888, 0.9515859766277128, 0.9332220367278798]

In [18]:
from sklearn.model_selection import cross_val_score

In [21]:
cross_val_score(LogisticRegression(solver='liblinear', max_iter=1000),digits.data,digits.target)

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

In [22]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [23]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.93333333, 0.91111111, 0.96935933, 0.94986072, 0.91643454])

In [24]:
cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target)

array([0.86111111, 0.83888889, 0.86908078, 0.91922006, 0.83286908])

In [25]:
cross_val_score(RandomForestClassifier(n_estimators=15),digits.data,digits.target)

array([0.9       , 0.86944444, 0.95264624, 0.93593315, 0.88857939])

In [26]:
cross_val_score(RandomForestClassifier(n_estimators=100),digits.data,digits.target)

array([0.93055556, 0.90555556, 0.95543175, 0.97214485, 0.93036212])